version: '3.8'

services:
  sales-dashboard:
    image: your-registry/sales-dashboard:latest
    ports:
      - "5000:5000"
    environment:
      # Configuração do Banco de Dados
      - DATABASE_URL=postgresql://neondb_owner:npg_LbGw9i6rWjAB@ep-weathered-cherry-acpldkqj-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
      - PGHOST=ep-weathered-cherry-acpldkqj-pooler.sa-east-1.aws.neon.tech
      - PGUSER=neondb_owner
      - PGPASSWORD=npg_LbGw9i6rWjAB
      - PGDATABASE=neondb
      - PGPORT=5432
      
      # Configuração do Node.js
      - NODE_ENV=production
      - PORT=5000
      
      # Configuração de Sessão
      - SESSION_SECRET=your-super-secret-session-key-change-this-in-production
      
      # Dados do SMTP
      - MAILER_USER=contato@meusuper.app
      - MAILER_PASSWORD=Pj2Nr0BdsfCTRnmM
      - MAILER_HOST=smtp-relay.brevo.com
      - MAILER_PORT=587
      
      # Configuração da Aplicação
      - APP_NAME=Dashboard de Vendas
      - APP_URL=https://your-domain.com
      
      # Configuração de CORS
      - ALLOWED_ORIGINS=https://your-domain.com,https://www.your-domain.com
      
      # Configuração de Logs
      - LOG_LEVEL=info
      
      # Rate Limiting
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      
    networks:
      - sales-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  sales-network:
    driver: overlay
    attachable: true